import type { ColorValue } from 'react-native';

type ColorTokens =
  | 'appBackground'
  | 'appForeground'
  | 'textPrimary'
  | 'controlStrongStrokeDefault'
  | 'accentDefault'
  | 'textOnAccentPrimary'
  | 'controlAltTertiary'
  | 'accentSecondary'
  | 'controlAltQuarternary'
  | 'controlStrongStrokeDisabled'
  | 'accentTertiary'
  | 'textOnAccentSecondary'
  | 'controlAltDisabled'
  | 'accentDisabled'
  | 'textOnAccentDisabled'
  | 'textDisabled'
  | 'fillColorControlSecondary'
  | 'fillColorControlTertiary'
  | 'fillColorControlDisabled'
  | 'fillColorTextDisabled'
  | 'fillColorTextPrimary'
  | 'fillColorTextSecondary'
  | 'fillColorAccentTextPrimary'
  | 'fillColorTextOnAccentPrimary'
  | 'fillColorControlDefault'
  | 'fillColorControlStrongDefault'
  | 'fillColorControlAltSecondary'
  | 'fillColorControlAltTertiary'
  | 'fillColorSubtleTransparent'
  | 'fillColorSubtleSecondary'
  | 'fillColorAccentDefault'
  | 'fillColorControlSolidDefault'
  | 'fillColorSystemCritical'
  | 'fillColorSystemCriticalBackground'
  | 'fillColorControlOnImageDefault'
  | 'strokeColorControlStrongStrokeDefault'
  | 'strokeColorDividerStrokeDefault'
  | 'strokeColorSurfaceStrokeDefault'
  | 'strokeColorCardStrokeDefault'
  | 'strokeColorFocusStrokeInner'
  | 'backgroundFillColorCardBackgroundDefault'
  | 'backgroundFillColorCardBackgroundSecondary'
  | 'backgroundFillColorSmokeDefault'
  | 'backgroundFillColorLayerDefault'
  | 'backgroundFillColorLayerOnAcrylicDefault'
  | 'backgroundFillColorAcrylicBackgroundDefault'
  | 'backgroundFillColorAcrylicBackgroundBase'
  | 'backgroundFillColorAccentAcrylicBackgroundBase'
  | 'backgroundFillColorLayerOnMicaBaseAltDefault'
  | 'backgroundFillColorMicaBackgroundBase'
  | 'backgroundFillColorSolidBackgroundBase'
  | 'backgroundFillColorSolidBackgroundSecondary'
  | 'strokeColorSurfaceStrokeFlayout'
  | 'contextMenuBackgroundSolid'
  | 'controlAltSecondary';

export type Colors = {
  readonly [key in ColorTokens]: ColorValue;
};
